language: node_js
node_js:
  - "6"
deploy:
  provider: npm
  email: vi@ole.org
  api_key:
    secure: "O/RgqETfw9NR36/OIwygPTExRWZ6hAMOD3Sr21XKNcXZ+8VniY9qgFrfcASjiC/QHWh2uhhn1mlb+5xtETPH2PKEaBrVHaGwdv5vJFlRzbfvl6QD/S4tPcMvQBIWfPGogj907yBiL6KTTvej17bRnX7g3dO3k6KkbIfPktlD6aBZXVoMjhSWBz++PUrq8+hHLshQInp9O8xgQa1+llioZaP5oPB9YQJxjvL5SJkOZMfgt4CKtTcjOubTl8F+SS0J7Zt2JbZrvmg7tzTCq8Tw5D3qIZpe/sEyeb5EPsf7ZIljZfqa74v3GvGFilaCH0U0mWczO30MxjlRExLgvNabUZDqQ7FK5zgpSysK8QWe6OZYHVHQfGsP/Zb8pyLpjZB8zTQWGX+igqkUdQbE0X3lTBlp0vZByKOSo9lWlz9hSGjeAgKG7VrZUQCHZ02noyjz59wJzujOp3JqaOfvCGU1qjwyPMZErQ++6T7OYHiPK561esgLEPp3sPmfLZySqBHlLtdl/Djl9NKqrRgZi7pnqVCzzsYcrTsnR9eLE7C7I63YXWQQ5PNgL8jINwBPe5vI2vEAQZsioNLC95EM3P2UGb+TF9xp731SoBkA0ji3acoqvh+Gl5uM7y0g947Pf6EEQSCH0/NubMlS5w8KExpbX/smhhUrYHzbHHUuqHho8bY="
    #secure: "S/3GT6fDWifqlyiCpsEzo3K9/Jdc3tb/rfOfnX11ji1G4VzQln5jHLYIZQYZHhqTEH0DJtkElSLH/Co+tEClwYP/VAhn7pPhYujiQIjDxCDMoMiigfTkXb0/YTTRREyjYKb6+qKJnVf+jBx73gyXwFbQEn6qo48KXWSJrqdtuTYQpFeOj+E4cBR8Eflq381slpzU1L8BDLz8j2hguKTdhIk9OxWSFmI/s7R9pdFRIbH2VkDyDBiR1+qiIt5Au3jgYG9ziv8sJxWvRLc2jhDfbaacjfSxcWWaScy7weSDI4dpZtl5zuu6ElGWO1+z5U2qw/IALpRp14j9YpvmlMpVp4lfgLgdZ1pLyBWfz/Wr7vXEZ5q4x6K6GX84HOP93UCxUey3iAq9lDwta8pdDy7q69PK1vUYHVQtP9och8VkftmrB/fqRWeyn7iHbHh6/JGme6ZpESsGVSF1vK01OUmwtClRqqo5s77ESh+UGaLHwEnaTWKRwhy4a/8HBOK8uop8STo8kXgfnea94sNYPL0Y3gUs3gtlraitUcUUk2CebAMf6DiScqAtZorpsUT7nqqj0cLzFuidZmBWZPNLv8iRQs3oEP/UH9DP2BlBQj85FEos0CYxy6MMV905tD7Tm0YHs6rtlntaI4LtFLRhmammsTPvGCy0YOIxjFr7Q2P4ZDw="
  skip_cleanup: true
  on:
    tags: true
    repo: treehouses/cli
