name: publish on npmjs.org

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: treehouses/cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - name: build
        run: |
          ./templates/blocker/blocker.sh
          ls -al ./templates/blocker/
          sudo npm install -g auto-changelog
          auto-changelog --version
          auto-changelog --template .github/workflows/changelog-template.hbs
          sync
          sed -i -e "s#&lt;#<#g" CHANGELOG.md
          sed -i -e "s#&gt;#>#g" CHANGELOG.md
          ls -al
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
