name: npmjs.org

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: treehouses/cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - name: build
        run: |
          ./templates/blocker/blocker.sh
          ls -al ./templates/blocker/
          sudo npm install -g auto-changelog
          cat .travis/changelog-template.hbs
          auto-changelog --version
          git tag > list
          cat list
          auto-changelog --template .travis/changelog-template.hbs
          sed -i -e "s#&lt;#<#g" CHANGELOG.md
          sed -i -e "s#&gt;#>#g" CHANGELOG.md
          ls -al
          cat CHANGELOG.md
      - name: publish
        run: echo "npm publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
